defaults:
    - base

task: "fs_search"

data:
    name: "visual_genome"
    path: "${paths.data_dir}/${vision.data.name}"
    num_images: 108077
    use_percentage: 0.2
    num_loader_workers: 4
    batch_size: 64
    num_exs_per_conc: 10
    batch_size_eval: 1
    num_exs_per_conc_eval: 10

optim:
    init_lr: 6e-4
    # algorithm: "SGD"
    # momentum_1m: 1e-1
    algorithm: "Adam"
    beta1_1m: 1e-1
    beta2_1m: 1e-3
    eps: 1e-8
    lr_scheduler: "MultiStepLR"
    lr_scheduler_milestones:
        - 0.9
    lr_scheduler_gamma: 3e-1
    max_steps: 500          # Total iterations = data.batch_size * optim.max_steps
    log_interval: 5         # Logged to W&B every data.batch_size * optim.log_interval iterations
    val_interval: 3200
    compress_eval: True