defaults:
    - base

task: "fs_search"

data:
    name: "visual_genome"
    path: "${paths.data_dir}/${vision.data.name}"
    num_images: 108077
    use_percentage: 0.2
    num_loader_workers: 4
    batch_size: 5
    num_exs_per_conc: 5
    batch_size_eval: 10
    num_exs_per_conc_eval: 10

optim:
    init_lr: 1e-4
    algorithm: "SGD"
    momentum_1m: 1e-1
    # algorithm: "Adam"
    beta1_1m: 1e-1
    beta2_1m: 1e-3
    eps: 1e-8
    lr_scheduler: "MultiStepLR"
    lr_scheduler_milestones:
        - 0.9
    lr_scheduler_gamma: 3e-1
    max_steps: 6000
    log_interval: 50
    val_interval: 2000