defaults:
    - base

task: "fs_search"

data:
    name: "tabletop"
    path: "${paths.data_dir}/${vision.data.name}"
    num_loader_workers: 4
    batch_size: 16
    num_exs_per_conc: 10
    batch_size_eval: 5
    num_exs_per_conc_eval: 10

optim:
    init_lr: 3e-5
    # algorithm: "SGD"
    # momentum_1m: 1e-1
    algorithm: "Adam"
    beta1_1m: 1e-1
    beta2_1m: 1e-3
    eps: 1e-8
    lr_scheduler: "MultiStepLR"
    lr_scheduler_milestones:
        - 0.9
    lr_scheduler_gamma: 3e-1
    max_steps: 1000
    log_interval: 10        # Note: Logged to W&B every data.batch_size * optim.log_interval iterations
    val_interval: 1600
    compress_eval: False