defaults:
    - base

data:
    name: visual_genome
    path: "${paths.data_dir}/${vision.data.name}"
    num_images: 108077
    use_percentage: 0.1
    num_loader_workers: 4
    batch_size: 64
    num_exs_per_conc: 8

optim:
    algorithm: "SGD"
    max_epochs: 10
    learning_rate: 0.0001
    lr_schedule: "MultiStepLR"
    lr_gamma: 0.1

task: ???
