defaults:
    - vision: base
    - lang: base

paths:
    root_dir: "${hydra:runtime.cwd}"
    data_dir: "${paths.root_dir}/datasets"
    assets_dir: "${paths.root_dir}/assets"
    outputs_dir: "${hydra:runtime.output_dir}"

agent:
    strat_generic: "semOnly"
    strat_mismatch: "zeroinit"

exp1:
    strat_feedback: "min"
    difficulty: "nonFine"
    num_episodes: 50
    test_set_size: 30

seed: 42